"""Added bookings, hotels, rooms, users(1)

Revision ID: d9b993f4a21f
Revises: 4add8b50bfbb
Create Date: 2023-11-07 21:03:04.356749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9b993f4a21f'
down_revision: Union[str, None] = '4add8b50bfbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
